security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    providers:
        users_in_memory:
            memory:
                users:
                    admin@exemple.com:
                        password: '$2y$13$s9yldOnH4SlOw9U8UEs8F.yWx7EZtTqciSNgffTbAOBnj/7IwCC0y' # Mot de passe : admin
                        roles: ['ROLE_ADMIN']
                    user@exemple.com:
                        password: '$2y$13$bAjdC3uTYhQgyztwh554uOjFo4GJPZ0rF06sAx8qw6ZzUj/EfW9Ci' # Mot de passe : user
                        roles: ['ROLE_USER']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/  
            security: false

        main:
            lazy: true
            provider: users_in_memory
            custom_authenticator: App\Security\AppAuthenticator
            form_login:
                login_path: login
                check_path: login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /
            logout:
                path: /logout
                target: /login
            entry_point: App\Security\AppAuthenticator # ✅ Définit l'authenticator principal

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/account, roles: ROLE_USER }
