security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    providers:
        app_user_provider:  # ✅ Utilisation de la base de données comme provider
            entity:
                class: App\Entity\User  # ✅ On utilise l'entité User
                property: email  # ✅ L'identifiant de connexion est l'email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/  
            security: false

        main:
            lazy: true
            provider: app_user_provider  # ✅ On utilise la base de données pour les utilisateurs
            custom_authenticator: App\Security\AppAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /
            logout:
                path: app_logout
                target: app_login
            entry_point: App\Security\AppAuthenticator # ✅ Définit l'authenticator principal

    access_control:
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        - { path: ^/user-dashboard, roles: ROLE_USER }
